enum SettingKey {
  logoPosition,
  invoicePrefix,
  additionalInfo,
  thankYouNote,
  currency,
  upiId, // kept for backward-compat read only
  showUpiQr,
  upiIds, // JSON list of UpiEntry objects
  showGstFields, // whether to show GST/GSTIN fields
  fractionalQuantity, // whether to allow decimal quantities (e.g. 1.5 hrs)
  quantityLabel, // default label for the Qty column (e.g. "Words", "Hours")
  logoSize, // logo size on PDF: 'xsmall' | 'small' | 'medium' | 'large'
  businessType, // 'product' | 'service' | 'both'
  showQuantity, // whether to show quantity field (default true)
  bankAccounts, // JSON list of BankAccount objects
  showBankDetails, // whether to show bank details on PDF
  showPhone, // whether to show company phone on PDF (default true)
  showEmail, // whether to show company email on PDF (default true)
  showDiscount, // whether to show discount column on PDF (default true)
  showTypeTag, // whether to show product/service tag on invoice items (default true)
  lastUpdateCheck, // ISO timestamp of last GitHub release API call
  lastKnownLatestVersion, // latest version tag returned by last API call
  lastNotifiedVersion, // version for which the update dialog was last shown
  dateFormat, // date display pattern: 'dd/MM/yyyy' | 'MM/dd/yyyy' | 'dd MMM yyyy' | 'yyyy-MM-dd'
  showInvoiceFooterBranding, // show "Generated by Invoiso" in invoice PDF footer
  pdfThemeColor, // custom PDF accent/theme color as #RRGGBB
  dashboardLayout, // which dashboard layout to use: 'default' | 'classic' | 'simple'
  layoutBannerDismissed, // '1' once user dismisses the new-layouts discovery banner
  themeBannerDismissed, // '1' once user dismisses the dark-mode (beta) discovery banner
  signatureImage, // base64-encoded signature image
  signaturePosition, // 'left' | 'right'
  signatureSize, // signature size on PDF: 'small' | 'medium' | 'large'
  showPreviousBalance, // whether to show calculated Previous Balance Due on PDFs
  pageSize, // 'a4' | 'a6'
  showTotalQuantity, // show total quantity row in compact template footer
  supportBannerDismissed, // milestone at which support banner was last dismissed: '10' | '50' | '100'
  invoiceStartingNumber, // starting invoice number (only editable when invoice count is zero)
  invoiceLeadingZeros, // whether generated invoice numbers are zero-padded to 8 digits (default true; locked once invoices exist)
  defaultTaxRate, // default invoice tax rate percentage (e.g. '18')
  thermalWidthMargin, // chars trimmed off the thermal printer's textbook width to avoid edge clipping on real hardware; default '1'
  thermalItemLayout, // 'table' | 'detailed' — how items print on thermal receipts; default 'table'
  invoiceTemplate, // used by cloud edition's generic setSetting/getSetting path
  companyLogo, // used by cloud edition's generic setSetting/getSetting path
  installationId, // Unique identifier for this installation. Generated on first launch and persisted locally. Used for anonymous analytics and installation tracking.
  showAliasNameInPdf, // whether to print a product's local-language alias name instead of its actual name on PDFs (default false)
  showTaxButtonInInvoicePage,
  themeMode, // app theme: 'light' | 'dark' | 'system'
  watermarkImage, // base64-encoded watermark image shown behind invoice items table
  watermarkOpacity, // watermark opacity 0.0-1.0 as string; default '0.12'
  defaultInvoiceTitle, // GST document title preselected on new invoices: 'Tax Invoice' | 'Bill of Supply' | etc; null/empty = plain 'Invoice'
  allowDuplicateInvoiceItems, // whether the same product can be added twice to one invoice (default false)
  showCgstSgst, // whether to split tax into CGST/SGST (India, 50/50)
  defaultTaxMode, // 'global' | 'perItem' — default tax mode for new invoices
  showRoundOff, // whether to show round-off row + amount-in-words on PDFs (default false)
  showCompanyName, // whether to show company name on PDF (default true)
  showPan, // whether to show company PAN on PDF (default true)
  showFssai, // whether to show company FSSAI code on PDF (default true)
  showWebsite, // whether to show company website on PDF (default true)
  showAddress, // whether to show company address on PDF (default true)
  showLogo, // whether to show company logo on PDF (default true)
  productColumnsBannerDismissed, // '1' once user dismisses the product-columns discovery banner
  thermalCompanyNameSize, // 'xsmall' | 'small' | 'medium' | 'large' — company name font size on thermal receipts; default 'medium'
  lastUsedThermalPrinter, // JSON-encoded Printer of the last device successfully printed to, used to skip a full rescan on next open
  productColumnsConfig, // JSON ProductColumnsConfig — which optional product fields (and invoice extra cost) are visible/editable
  shortcutsBannerDismissed, // '1' once user dismisses the keyboard-shortcuts discovery banner
  createInvoiceLayout, // which create-invoice screen layout to use: 'v1' | 'v2'
  showCustomerStatsCards, // whether the stat cards row is shown on customer management v2 (default true)
  showProductStatsCards, // whether the stat cards row is shown on product management v2 (default true)
  hideInvoiceNumberByDefault, // whether the "Hide invoice number in PDF" toggle is on by default for new invoices (default false)
}

extension SettingKeyExtension on SettingKey {
  String get key {
    switch (this) {
      case SettingKey.logoPosition:
        return 'logo_position';
      case SettingKey.invoicePrefix:
        return 'invoice_prefix';
      case SettingKey.additionalInfo:
        return 'additional_info';
      case SettingKey.thankYouNote:
        return 'thank_you_note';
      case SettingKey.currency:
        return 'currency';
      case SettingKey.upiId:
        return 'upi_id';
      case SettingKey.showUpiQr:
        return 'show_upi_qr';
      case SettingKey.upiIds:
        return 'upi_ids';
      case SettingKey.showGstFields:
        return 'show_gst_fields';
      case SettingKey.fractionalQuantity:
        return 'fractional_quantity';
      case SettingKey.quantityLabel:
        return 'quantity_label';
      case SettingKey.logoSize:
        return 'logo_size';
      case SettingKey.businessType:
        return 'business_type';
      case SettingKey.showQuantity:
        return 'show_quantity';
      case SettingKey.bankAccounts:
        return 'bank_accounts';
      case SettingKey.showBankDetails:
        return 'show_bank_details';
      case SettingKey.showPhone:
        return 'show_phone';
      case SettingKey.showEmail:
        return 'show_email';
      case SettingKey.showDiscount:
        return 'show_discount';
      case SettingKey.showTypeTag:
        return 'show_type_tag';
      case SettingKey.lastUpdateCheck:
        return 'last_update_check';
      case SettingKey.lastKnownLatestVersion:
        return 'last_known_latest_version';
      case SettingKey.lastNotifiedVersion:
        return 'last_notified_version';
      case SettingKey.dateFormat:
        return 'date_format';
      case SettingKey.showInvoiceFooterBranding:
        return 'show_invoice_footer_branding';
      case SettingKey.pdfThemeColor:
        return 'pdf_theme_color';
      case SettingKey.dashboardLayout:
        return 'dashboard_layout';
      case SettingKey.layoutBannerDismissed:
        return 'layout_banner_dismissed';
      case SettingKey.themeBannerDismissed:
        return 'theme_banner_dismissed';
      case SettingKey.signatureImage:
        return 'signature_image';
      case SettingKey.signaturePosition:
        return 'signature_position';
      case SettingKey.signatureSize:
        return 'signature_size';
      case SettingKey.showPreviousBalance:
        return 'show_previous_balance';
      case SettingKey.pageSize:
        return 'page_size';
      case SettingKey.showTotalQuantity:
        return 'show_total_quantity';
      case SettingKey.supportBannerDismissed:
        return 'support_banner_dismissed';
      case SettingKey.invoiceStartingNumber:
        return 'invoice_starting_number';
      case SettingKey.invoiceLeadingZeros:
        return 'invoice_leading_zeros';
      case SettingKey.defaultTaxRate:
        return 'default_tax_rate';
      case SettingKey.thermalWidthMargin:
        return 'thermal_width_margin';
      case SettingKey.thermalItemLayout:
        return 'thermal_item_layout';
      case SettingKey.invoiceTemplate:
        return 'invoice_template';
      case SettingKey.companyLogo:
        return 'company_logo';
      case SettingKey.installationId:
        return 'installation_id';
      case SettingKey.showAliasNameInPdf:
        return 'show_alias_name_in_pdf';
      case SettingKey.showTaxButtonInInvoicePage:
        return 'show_tax_button_in_invoice_page';
      case SettingKey.themeMode:
        return 'theme_mode';
      case SettingKey.watermarkImage:
        return 'watermark_image';
      case SettingKey.watermarkOpacity:
        return 'watermark_opacity';
      case SettingKey.defaultInvoiceTitle:
        return 'default_invoice_title';
      case SettingKey.allowDuplicateInvoiceItems:
        return 'allow_duplicate_invoice_items';
      case SettingKey.showCgstSgst:
        return 'show_cgst_sgst';
      case SettingKey.defaultTaxMode:
        return 'default_tax_mode';
      case SettingKey.showRoundOff:
        return 'show_round_off';
      case SettingKey.showCompanyName:
        return 'show_company_name';
      case SettingKey.showPan:
        return 'show_pan';
      case SettingKey.showFssai:
        return 'show_fssai';
      case SettingKey.showWebsite:
        return 'show_website';
      case SettingKey.showAddress:
        return 'show_address';
      case SettingKey.showLogo:
        return 'show_logo';
      case SettingKey.productColumnsBannerDismissed:
        return 'product_columns_banner_dismissed';
      case SettingKey.thermalCompanyNameSize:
        return 'thermal_company_name_size';
      case SettingKey.lastUsedThermalPrinter:
        return 'last_used_thermal_printer';
      case SettingKey.productColumnsConfig:
        return 'product_columns_config';
      case SettingKey.shortcutsBannerDismissed:
        return 'shortcuts_banner_dismissed';
      case SettingKey.createInvoiceLayout:
        return 'create_invoice_layout';
      case SettingKey.showCustomerStatsCards:
        return 'show_customer_stats_cards';
      case SettingKey.showProductStatsCards:
        return 'show_product_stats_cards';
      case SettingKey.hideInvoiceNumberByDefault:
        return 'hide_invoice_number_by_default';

    }
  }
}
