name: invoiso
description: "Invoice generating desktop app built with Flutter"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 4.3.6
environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.3
  pdf: ^3.11.3
  printing: ^5.11.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.6
  path: ^1.8.3
  path_provider: ^2.0.15
  file_picker: ^10.2.0
  permission_handler: ^12.0.1
  share_plus: ^11.0.0
  crypto: ^3.0.3
  cryptography: ^2.7.0
  uuid: ^4.0.0
  csv: ^8.0.0
  archive: ^4.0.0
  flutter_riverpod: ^2.5.1
  open_file: ^3.3.2
  url_launcher: ^6.2.6
  http: ^1.6.0
  fl_chart: ^0.69.0
  syncfusion_flutter_pdfviewer: ^30.1.40
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  window_manager: ^0.5.1
  screen_retriever: ^0.2.2
  flutter_svg: ^2.3.0
  image: ^4.8.0
  qr: ^3.0.1
  flex_color_picker: ^3.6.0
  thermal_printer: ^1.0.5
  flutter_esc_pos_utils: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  package_rename: ^1.10.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
   - assets/images/logo.png
   - assets/images/logo_dark.png
   - assets/images/logo.svg
   - assets/images/logo_v.png
   - assets/images/logo_v_dark.png
   - assets/fonts/

flutter_launcher_icons:
  macos:
    generate: true
    image_path: "assets/images/logo_v.png"

package_rename_config:
  linux:
    app_name: invoiso
    package_name: invoiso
    exe_name: invoiso

  windows:
    app_name: invoiso
    organization: anoopp
    copyright_notice: Copyright ©️ 2025 anoopp. All rights reserved.
    exe_name: invoiso

  web:
    app_name: invoiso
    short_app_name: invoiso
    description: Invoice generating desktop app built with Flutter
