import 'package:invoiso/common/common.dart';

abstract class SettingsRepository {
  Future<void> setSetting(SettingKey key, String value);
  Future<String?> getSetting(SettingKey key);
  Future<void> deleteSetting(SettingKey key);
  Future<void> setInvoiceTemplate(InvoiceTemplate template);
  Future<InvoiceTemplate> getInvoiceTemplate();
  Future<void> setPdfThemeColor(String hexColor);
  Future<void> clearPdfThemeColor();
  Future<String?> getPdfThemeColor();
  Future<void> setCompanyLogo(String base64Logo);
  Future<String?> getCompanyLogo();
  Future<LogoPosition> getLogoPosition();
  Future<String> getLogoSize();
  Future<void> setCurrency(String currencyCode);
  Future<CurrencyOption> getCurrency();
  Future<List<UpiEntry>> getUpiIds();
  Future<void> setUpiIds(List<UpiEntry> entries);
  Future<List<BankAccount>> getBankAccounts();
  Future<void> setBankAccounts(List<BankAccount> accounts);
  Future<ProductColumnsConfig> getProductColumnsConfig();
  Future<void> setProductColumnsConfig(ProductColumnsConfig config);
  Future<bool> getShowBankDetails();
  Future<void> setShowBankDetails(bool show);
  Future<bool> getShowPhone();
  Future<void> setShowPhone(bool show);
  Future<bool> getShowEmail();
  Future<void> setShowEmail(bool show);
  Future<bool> getShowCompanyName();
  Future<void> setShowCompanyName(bool show);
  Future<bool> getShowPan();
  Future<void> setShowPan(bool show);
  Future<bool> getShowFssai();
  Future<void> setShowFssai(bool show);
  Future<bool> getShowWebsite();
  Future<void> setShowWebsite(bool show);
  Future<bool> getShowAddress();
  Future<void> setShowAddress(bool show);
  Future<bool> getShowLogo();
  Future<void> setShowLogo(bool show);
  Future<bool> getShowGstFields();
  Future<bool> getShowInvoiceFooterBranding();
  Future<bool> getFractionalQuantity();
  Future<String> getQuantityLabel();
  Future<bool> getShowQuantity();
  Future<void> setShowQuantity(bool show);
  Future<bool> getShowDiscount();
  Future<void> setShowDiscount(bool show);
  Future<bool> getShowTypeTag();
  Future<void> setShowTypeTag(bool show);
  Future<bool> getShowTotalQuantity();
  Future<void> setShowTotalQuantity(bool show);
  Future<bool> getShowPreviousBalance();
  Future<void> setShowPreviousBalance(bool show);
  Future<void> setSignatureImage(String base64Image);
  Future<String?> getSignatureImage();
  Future<void> setWatermarkImage(String base64Image);
  Future<String?> getWatermarkImage();
  Future<void> setWatermarkOpacity(double opacity);
  Future<double> getWatermarkOpacity();
  Future<void> setDefaultInvoiceTitle(String? title);
  Future<String?> getDefaultInvoiceTitle();
  Future<String> getSignaturePosition();
  Future<String> getDefaultTaxMode();
  Future<String> getSignatureSize();
  Future<BusinessType> getBusinessType();
  Future<void> setBusinessType(BusinessType type);
  Future<DateFormatOption> getDateFormat();
  Future<void> setDateFormat(DateFormatOption option);
  Future<PageSize> getPageSize();
  Future<void> setPageSize(PageSize size);
  Future<bool> getShowAliasNameInPdf();
  Future<bool> getShowTaxButtonInInvoicePage();
  Future<bool> getHideInvoiceNumberByDefault();
  Future<String> getThemeMode();
  Future<void> setThemeMode(String mode);
  Future<bool> getAllowDuplicateInvoiceItems();
  Future<void> setAllowDuplicateInvoiceItems(bool allow);
}
