import 'package:flutter/foundation.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:invoiso/common/common.dart';
import 'package:invoiso/common/constants.dart';
import 'package:invoiso/models/company_info.dart';
import 'package:invoiso/models/invoice.dart';
import 'pdf_widgets.dart';

pw.MultiPage buildMinimalTemplate(
  Invoice invoice,
  CompanyInfo? company,
  String currencySymbol,
  String invoicePrefix, {
  String? upiId,
  bool showUpiQr = false,
  bool showGst = true,
  bool showQuantity = true,
  bool showDiscount = true,
  bool showTypeTag = true,
  bool showAliasName = false,
  BusinessType businessType = BusinessType.both,
  BankAccount? bankAccount,
  String datePattern = 'dd/MM/yyyy',
  LogoPosition logoPosition = LogoPosition.left,
  double logoSizePx = 90,
  Uint8List? logoBytes,
  String thankYouNote = '',
  bool showFooterBranding = true,
  PdfColor? themeColor,
  Uint8List? signatureBytes,
  String signaturePosition = 'left',
  double signatureSizePx = 50,
  double previousBalanceDue = 0.0,
  PdfPageFormat pageFormat = PdfPageFormat.a4,
  pw.ThemeData? pdfTheme,
  Uint8List? watermarkBytes,
  double watermarkOpacity = 0.12,
  bool showCgstSgst = false,
  bool showRoundOff = false,
  bool showLeadingZeros = true,
  bool showPhone = true,
  bool showEmail = true,
  bool showCompanyName = true,
  bool showPan = true,
  bool showFssai = true,
  bool showWebsite = true,
  bool showAddress = true,
  bool showLogo = true,
}) {
  final accentColor = themeColor ?? PdfColors.grey700;
  final logoImage = logoBytes != null ? pw.MemoryImage(logoBytes) : null;
  final signatureImage =
      signatureBytes != null ? pw.MemoryImage(signatureBytes) : null;
  final thankyouNote = thankYouNote;

  final title = (invoice.invoiceTitle?.trim().isNotEmpty ?? false)
      ? invoice.invoiceTitle!.toUpperCase()
      : invoice.type.toUpperCase();

  final gstin = company?.gstin ?? '';
  final gstLabel = taxLabel(company?.country);
  final panNumber = company?.panNumber ?? '';
  final fssaiCode = company?.fssaiCode ?? '';
  final companyIdLine = [
    if (showGst && gstin.isNotEmpty) '$gstLabel: $gstin',
    if (showPan && panNumber.isNotEmpty) '${panLabel(company?.country)}: $panNumber',
    if (showFssai && fssaiCode.isNotEmpty) 'FSSAI: $fssaiCode',
  ].join('   ');

  return pw.MultiPage(
    pageFormat: pageFormat,
    theme: pdfTheme,
    margin: pw.EdgeInsets.all(PdfLayout.defaultHMargin),
    footer: (context) => pw.Container(
      alignment: pw.Alignment.centerRight,
      margin: const pw.EdgeInsets.only(top: 20),
      child: pw.Text(
        showFooterBranding
            ? "Page ${context.pageNumber} of ${context.pagesCount}  -  Generated by Invoiso"
            : "Page ${context.pageNumber} of ${context.pagesCount}",
        style: pw.TextStyle(fontSize: PdfLayout.footerBrandingFontSize, color: PdfColors.grey600),
      ),
    ),
    build: (context) => [
      if(logoImage == null || !showLogo)
        pw.Row(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                if (invoice.pdfNumberText(invoicePrefix, showLeadingZeros: showLeadingZeros) != null)
                  pw.Text(invoice.pdfNumberText(invoicePrefix, showLeadingZeros: showLeadingZeros)!,
                      style: pw.TextStyle(fontSize: minimalPdfStyle.bodyFontSize)),
                pw.SizedBox(height: minimalPdfStyle.headerGap)
              ],
            ),
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                pw.Text("DATE",
                    style: pw.TextStyle(
                        fontWeight: pw.FontWeight.bold,
                        fontSize: minimalPdfStyle.labelFontSize,
                        color: accentColor)),
                pw.Text(formatPdfDate(invoice.date, datePattern),
                    style: pw.TextStyle(fontSize: minimalPdfStyle.bodyFontSize)),
                if (invoice.dueDate != null) ...[
                  pw.SizedBox(height: minimalPdfStyle.headerGap),
                  pw.Text("DUE DATE",
                      style: pw.TextStyle(
                          fontWeight: pw.FontWeight.bold,
                          fontSize: minimalPdfStyle.labelFontSize,
                          color: accentColor)),
                  pw.Text(formatPdfDate(invoice.dueDate!, datePattern),
                      style: pw.TextStyle(fontSize: minimalPdfStyle.bodyFontSize)),
                ],
              ],
            ),
          ],
      ),
      if(showLogo && logoImage != null)
        pw.Row(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            if (logoPosition == LogoPosition.left)
              buildCompanyLogo(logoImage, size: logoSizePx),
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                if (invoice.pdfNumberText(invoicePrefix, showLeadingZeros: showLeadingZeros) != null)
                  pw.Text(invoice.pdfNumberText(invoicePrefix, showLeadingZeros: showLeadingZeros)!,
                      style: pw.TextStyle(fontSize: minimalPdfStyle.bodyFontSize)),
                pw.SizedBox(height: minimalPdfStyle.headerGap),
                pw.Text("DATE",
                    style: pw.TextStyle(
                        fontWeight: pw.FontWeight.bold,
                        fontSize: minimalPdfStyle.labelFontSize,
                        color: accentColor)),
                pw.Text(formatPdfDate(invoice.date, datePattern),
                    style: pw.TextStyle(fontSize: minimalPdfStyle.bodyFontSize)),
                if (invoice.dueDate != null) ...[
                  pw.SizedBox(height: minimalPdfStyle.headerGap),
                  pw.Text("DUE DATE",
                      style: pw.TextStyle(
                          fontWeight: pw.FontWeight.bold,
                          fontSize: minimalPdfStyle.labelFontSize,
                          color: accentColor)),
                  pw.Text(formatPdfDate(invoice.dueDate!, datePattern),
                      style: pw.TextStyle(fontSize: minimalPdfStyle.bodyFontSize)),
                ],
              ],
            ),
            if (logoPosition == LogoPosition.right)
              buildCompanyLogo(logoImage, size: logoSizePx),
          ],
        ),
      pw.SizedBox(height: 5),
      pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceEvenly,
          children: [
        if(showPhone && (company?.phone ?? '').isNotEmpty)
          pw.Text(
            company?.phone != null && company!.phone!.isNotEmpty
                ? 'Ph: ${company.phone}'
                : '',
            style: pw.TextStyle(fontSize: minimalPdfStyle.bodyFontSize),
          ),
        if(showEmail && (company?.email ?? '').isNotEmpty)
          pw.Text(company?.email ?? '',
            style: pw.TextStyle(fontSize: minimalPdfStyle.bodyFontSize)),
        if (showWebsite && (company?.website ?? '').isNotEmpty)
          pw.Text(company!.website,
              style: pw.TextStyle(fontSize: minimalPdfStyle.bodyFontSize)),
      ]),
      pw.Divider(thickness: 0.5, color: PdfColors.grey400),
      pw.SizedBox(height: 2),
      pw.Center(child: pw.Text(title,
          style: pw.TextStyle(
              fontWeight: pw.FontWeight.bold,
              fontSize: minimalPdfStyle.titleFontSize,
              color: accentColor)),),
      pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text("FROM",
                  style: pw.TextStyle(
                      fontWeight: pw.FontWeight.bold,
                      fontSize: minimalPdfStyle.labelFontSize,
                      color: accentColor)),
              pw.SizedBox(height: minimalPdfStyle.headerGap),
              pw.Text(showCompanyName ? (company?.name ?? '') : '',
                  style: pw.TextStyle(
                      fontWeight: pw.FontWeight.bold, fontSize: minimalPdfStyle.titleFontSize)),
              if (showAddress)
                pw.Text(company?.address ?? '',
                    style: pw.TextStyle(fontSize: minimalPdfStyle.bodyFontSize)),
              if (companyIdLine.isNotEmpty)
                pw.Text(companyIdLine,
                    style: pw.TextStyle(
                        fontStyle: pw.FontStyle.italic, fontSize: minimalPdfStyle.bodyFontSize)),
            ],
          ),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              pw.Text("BILL TO",
                  style: pw.TextStyle(
                      fontWeight: pw.FontWeight.bold,
                      fontSize: minimalPdfStyle.labelFontSize,
                      color: accentColor)),
              pw.SizedBox(height: minimalPdfStyle.headerGap),
              pw.Text(invoice.customer.name,
                  style: pw.TextStyle(
                      fontWeight: pw.FontWeight.bold, fontSize: minimalPdfStyle.bodyFontSize)),
              if (invoice.customer.businessName.isNotEmpty)
                pw.Text(invoice.customer.businessName,
                    style: pw.TextStyle(fontSize: minimalPdfStyle.bodyFontSize)),
              pw.Text(invoice.customer.address,
                  style: pw.TextStyle(fontSize: minimalPdfStyle.bodyFontSize)),
              pw.Text(invoice.customer.phone,
                  style: pw.TextStyle(fontSize: minimalPdfStyle.bodyFontSize)),
              pw.Text(invoice.customer.email,
                  style: pw.TextStyle(fontSize: minimalPdfStyle.bodyFontSize)),
              if (showGst && invoice.customer.gstin.isNotEmpty)
                pw.Text(
                    "${taxLabel(company?.country)}: ${invoice.customer.gstin}",
                    style: pw.TextStyle(
                        fontStyle: pw.FontStyle.italic, fontSize: minimalPdfStyle.bodyFontSize)),
            ],
          ),
        ],
      ),

      pw.SizedBox(height: 5),

      buildInvoiceTable(invoice,
          InvoiceTemplate.minimal,
          headerColor: PdfColors.grey100,
          textColor: PdfColors.black,
          showGst: showGst,
          showQuantity: showQuantity,
          showDiscount: showDiscount,
          showTypeTag: showTypeTag,
          showAliasName: showAliasName,
          businessType: businessType,
          watermarkBytes: watermarkBytes,
          watermarkOpacity: watermarkOpacity,
          tableFontSize: minimalPdfStyle.tableFontSize,
          showCgstSgst: showCgstSgst),

      pw.SizedBox(height: 5),

      pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Expanded(child: buildAdditionalNotes(invoice, accentColor: accentColor)),
          pw.SizedBox(width: 20),
          buildEnhancedTotals(
            invoice,
            PdfColors.grey200,
            PdfColors.black,
            accentColor,
            currencySymbol,
            previousBalanceDue: previousBalanceDue,
            fontSize: minimalPdfStyle.totalsFontSize,
            showCgstSgst: showCgstSgst,
            showRoundOff: showRoundOff,
          ),
        ],
      ),

      if (signatureImage != null || (showUpiQr && upiId != null) || bankAccount != null) ...[
        pw.SizedBox(height: 5),
        pw.Row(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: signaturePosition == 'right'
              ? [
                  buildBankUpiRow(
                    bankAccount: bankAccount,
                    showUpiQr: showUpiQr,
                    upiId: upiId,
                    companyName: company?.name ?? '',
                    amount: invoice.total,
                    currencyCode: invoice.currencyCode,
                    invoiceId: invoice.id,
                    accentColor: accentColor,
                  ),
                  signatureImage != null
                      ? buildSignatureWidget(signatureImage, signaturePosition,
                          imageHeight: signatureSizePx)
                      : pw.SizedBox(),
                ]
              : [
                  signatureImage != null
                      ? buildSignatureWidget(signatureImage, signaturePosition,
                          imageHeight: signatureSizePx)
                      : pw.SizedBox(),
                  buildBankUpiRow(
                    bankAccount: bankAccount,
                    showUpiQr: showUpiQr,
                    upiId: upiId,
                    companyName: company?.name ?? '',
                    amount: invoice.total,
                    currencyCode: invoice.currencyCode,
                    invoiceId: invoice.id,
                    accentColor: accentColor,
                  ),
                ],
        ),
      ],

      pw.SizedBox(height: 20),

      pw.Center(
        child: pw.Text(thankyouNote,
            style: pw.TextStyle(
                color: accentColor,
                fontSize: PdfLayout.thankYouNoteFontSize,
                fontWeight: pw.FontWeight.bold)),
      ),
    ],
  );
}
