import 'package:flutter/foundation.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:invoiso/common/common.dart';
import 'package:invoiso/common/constants.dart';
import 'package:invoiso/models/company_info.dart';
import 'package:invoiso/models/invoice.dart';
import 'pdf_widgets.dart';

pw.MultiPage buildClassicTemplate(
  Invoice invoice,
  CompanyInfo? company,
  String currencySymbol,
  String invoicePrefix, {
  String? upiId,
  bool showUpiQr = false,
  bool showGst = true,
  bool showQuantity = true,
  bool showDiscount = true,
  bool showTypeTag = true,
  bool showAliasName = false,
  BusinessType businessType = BusinessType.both,
  BankAccount? bankAccount,
  String datePattern = 'dd/MM/yyyy',
  LogoPosition logoPosition = LogoPosition.left,
  double logoSizePx = 90,
  Uint8List? logoBytes,
  String thankYouNote = '',
  bool showFooterBranding = true,
  PdfColor? themeColor,
  Uint8List? signatureBytes,
  String signaturePosition = 'left',
  double signatureSizePx = 50,
  double previousBalanceDue = 0.0,
  PdfPageFormat pageFormat = PdfPageFormat.a4,
  pw.ThemeData? pdfTheme,
  Uint8List? watermarkBytes,
  double watermarkOpacity = 0.12,
  bool showCgstSgst = false,
  bool showRoundOff = false,
  bool showLeadingZeros = true,
  bool showPhone = true,
  bool showEmail = true,
  bool showCompanyName = true,
  bool showPan = true,
  bool showFssai = true,
  bool showWebsite = true,
  bool showAddress = true,
  bool showLogo = true,
}) {
  final accentColor = themeColor ?? PdfColors.indigo900;
  final logoImage = logoBytes != null ? pw.MemoryImage(logoBytes) : null;
  final signatureImage =
      signatureBytes != null ? pw.MemoryImage(signatureBytes) : null;
  final thankyouNote = thankYouNote;
  final title = (invoice.invoiceTitle?.trim().isNotEmpty ?? false)
      ? invoice.invoiceTitle!.toUpperCase()
      : invoice.type.toUpperCase();
  final gstin = company?.gstin ?? '';
  final gstLabel = taxLabel(company?.country);
  final panNumber = company?.panNumber ?? '';
  final fssaiCode = company?.fssaiCode ?? '';
  final companyIdLine = [
    if (showGst && gstin.isNotEmpty) '$gstLabel: $gstin',
    if (showPan && panNumber.isNotEmpty) '${panLabel(company?.country)}: $panNumber',
    if (showFssai && fssaiCode.isNotEmpty) 'FSSAI: $fssaiCode',
  ].join('   ');

  return pw.MultiPage(
    pageFormat: pageFormat,
    theme: pdfTheme,
    margin: pw.EdgeInsets.all(PdfLayout.defaultHMargin),
    footer: (context) => pw.Container(
      alignment: pw.Alignment.centerRight,
      margin: const pw.EdgeInsets.only(top: 20),
      child: pw.Text(
        showFooterBranding
            ? "Page ${context.pageNumber} of ${context.pagesCount}  -  Generated by Invoiso"
            : "Page ${context.pageNumber} of ${context.pagesCount}",
        style: pw.TextStyle(fontSize: PdfLayout.footerBrandingFontSize, color: PdfColors.grey600),
      ),
    ),
    build: (context) => [
      pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          if (showLogo && logoImage != null && logoPosition == LogoPosition.left)
            buildCompanyLogo(logoImage, size: logoSizePx),
          pw.Container(
            padding:
                const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 8),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey100,
              borderRadius: pw.BorderRadius.circular(4),
              border: pw.Border.all(color: PdfColors.grey300, width: 0.5),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(showCompanyName ? (company?.name ?? '') : '',
                    style: pw.TextStyle(
                        fontSize: classicPdfStyle.titleFontSize,
                        fontWeight: pw.FontWeight.bold,
                        color: accentColor)),
                pw.SizedBox(height: 4),
                if (showAddress)
                  pw.Text(company?.address ?? '',
                      style: pw.TextStyle(fontSize: classicPdfStyle.subtitleFontSize)),
                if (showPhone)
                  pw.Text('Phone: ${company?.phone ?? ''}',
                      style: pw.TextStyle(fontSize: classicPdfStyle.subtitleFontSize)),
                if (showEmail)
                  pw.Text('Email: ${company?.email ?? ''}',
                      style: pw.TextStyle(fontSize: classicPdfStyle.subtitleFontSize)),
                if (showWebsite && (company?.website ?? '').isNotEmpty)
                  pw.Text('Web: ${company!.website}',
                      style: pw.TextStyle(fontSize: classicPdfStyle.subtitleFontSize)),
              ],
            ),
          ),
          if (showLogo && logoImage != null && logoPosition == LogoPosition.right)
            buildCompanyLogo(logoImage, size: logoSizePx),
        ],
      ),

      pw.SizedBox(height: 6),
      if (companyIdLine.isNotEmpty)
        pw.Center(child: pw.Text(companyIdLine,
            style: pw.TextStyle(
                fontStyle: pw.FontStyle.normal,
                fontSize: classicPdfStyle.subtitleFontSize,
                color: PdfColors.grey700)),),
      pw.Divider(thickness: 1, color: accentColor),
      //pw.SizedBox(height: classicPdfStyle.headerGap),
      pw.Center(child: pw.Text(title,
        style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: classicPdfStyle.typeFont),),),
      pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Container(
                padding: pw.EdgeInsets.symmetric(horizontal: classicPdfStyle.sectionPadding, vertical: classicPdfStyle.sectionPadding),
                color: PdfColors.grey200,
                child: pw.Text("BILL TO",
                    style: pw.TextStyle(
                        fontWeight: pw.FontWeight.bold,
                        fontSize: classicPdfStyle.labelFontSize,
                        color: PdfColors.grey700)),
              ),
              pw.Padding(
                padding: pw.EdgeInsets.symmetric(horizontal: classicPdfStyle.sectionPadding, vertical: classicPdfStyle.sectionPadding),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.SizedBox(height: classicPdfStyle.headerGap),
                    pw.Text(invoice.customer.name,
                        style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: classicPdfStyle.bodyFontSize)),
                    if (invoice.customer.businessName.isNotEmpty)
                      pw.Text(invoice.customer.businessName,
                          style: pw.TextStyle(fontSize: classicPdfStyle.bodyFontSize)),
                    pw.Text(invoice.customer.address,
                        style: pw.TextStyle(fontSize: classicPdfStyle.bodyFontSize)),
                    pw.Text(invoice.customer.phone,
                        style: pw.TextStyle(fontSize: classicPdfStyle.bodyFontSize)),
                    pw.Text(invoice.customer.email,
                        style: pw.TextStyle(fontSize: classicPdfStyle.bodyFontSize)),
                    if (showGst)
                      pw.Text(
                          "${taxLabel(company?.country)}: ${invoice.customer.gstin}",
                          style: pw.TextStyle(
                              fontStyle: pw.FontStyle.italic,
                              fontSize: classicPdfStyle.subtitleFontSize,
                              color: PdfColors.grey600)),
                  ],
                ),
              ),
            ],
          ),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              if (invoice.pdfNumberText(invoicePrefix, showLeadingZeros: showLeadingZeros) != null)
                pw.Text(
                    "#: ${invoice.pdfNumberText(invoicePrefix, showLeadingZeros: showLeadingZeros)}",
                    style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: classicPdfStyle.subtitleFontSize)),
              pw.Text("Date: ${formatPdfDate(invoice.date, datePattern)}",
                  style: pw.TextStyle(fontSize: classicPdfStyle.bodyFontSize)),
              if (invoice.dueDate != null)
                pw.Text("Due Date: ${formatPdfDate(invoice.dueDate!, datePattern)}",
                    style: pw.TextStyle(fontSize: classicPdfStyle.bodyFontSize)),
            ],
          ),
        ],
      ),
      pw.SizedBox(height: 5),
      buildInvoiceTable(invoice,
          InvoiceTemplate.classic,
          headerColor: accentColor,
          textColor: PdfColors.white,
          showGst: showGst,
          showQuantity: showQuantity,
          showDiscount: showDiscount,
          showTypeTag: showTypeTag,
          showAliasName: showAliasName,
          businessType: businessType,
          watermarkBytes: watermarkBytes,
          watermarkOpacity: watermarkOpacity,
          showCgstSgst: showCgstSgst,
          tableFontSize: classicPdfStyle.tableFontSize,
          cellPaddingH: classicPdfStyle.cellPaddingH,
          cellPaddingV: classicPdfStyle.cellPaddingV),

      pw.SizedBox(height: 5),

      pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Expanded(child: buildAdditionalNotes(invoice, accentColor: accentColor)),
          pw.SizedBox(width: 20),
          buildEnhancedTotals(
            invoice,
            PdfColors.grey200,
            PdfColors.black,
            accentColor,
            currencySymbol,
            previousBalanceDue: previousBalanceDue,
            showCgstSgst: showCgstSgst,
            showRoundOff: showRoundOff,
            fontSize: classicPdfStyle.totalsFontSize,
          ),
        ],
      ),

      if (signatureImage != null || (showUpiQr && upiId != null) || bankAccount != null) ...[
        pw.SizedBox(height: 5),
        pw.Row(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: signaturePosition == 'right'
              ? [
                  buildBankUpiRow(
                    bankAccount: bankAccount,
                    showUpiQr: showUpiQr,
                    upiId: upiId,
                    companyName: company?.name ?? '',
                    amount: invoice.total,
                    currencyCode: invoice.currencyCode,
                    invoiceId: invoice.id,
                    accentColor: accentColor,
                  ),
                  signatureImage != null
                      ? buildSignatureWidget(signatureImage, signaturePosition,
                          imageHeight: signatureSizePx)
                      : pw.SizedBox(),
                ]
              : [
                  signatureImage != null
                      ? buildSignatureWidget(signatureImage, signaturePosition,
                          imageHeight: signatureSizePx)
                      : pw.SizedBox(),
                  buildBankUpiRow(
                    bankAccount: bankAccount,
                    showUpiQr: showUpiQr,
                    upiId: upiId,
                    companyName: company?.name ?? '',
                    amount: invoice.total,
                    currencyCode: invoice.currencyCode,
                    invoiceId: invoice.id,
                    accentColor: accentColor,
                  ),
                ],
        ),
      ],

      pw.SizedBox(height: 5),
      pw.Center(
        child: pw.Text(thankyouNote,
            style: pw.TextStyle(
                fontSize: PdfLayout.thankYouNoteFontSize,
                color: accentColor,
                fontStyle: pw.FontStyle.italic,
                fontWeight: pw.FontWeight.bold)),
      ),
    ],
  );
}
