import 'package:flutter/foundation.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:invoiso/common/common.dart';
import 'package:invoiso/common/constants.dart';
import 'package:invoiso/models/company_info.dart';
import 'package:invoiso/models/invoice.dart';
import 'pdf_widgets.dart';

pw.MultiPage buildExecutiveTemplate(
  Invoice invoice,
  CompanyInfo? company,
  String currencySymbol,
  String invoicePrefix, {
  String? upiId,
  bool showUpiQr = false,
  bool showGst = true,
  bool showQuantity = true,
  bool showDiscount = true,
  bool showTypeTag = true,
  bool showAliasName = false,
  BusinessType businessType = BusinessType.both,
  BankAccount? bankAccount,
  String datePattern = 'dd/MM/yyyy',
  LogoPosition logoPosition = LogoPosition.left,
  double logoSizePx = 90,
  Uint8List? logoBytes,
  String thankYouNote = '',
  bool showFooterBranding = true,
  PdfColor? themeColor,
  Uint8List? signatureBytes,
  String signaturePosition = 'left',
  double signatureSizePx = 50,
  double previousBalanceDue = 0.0,
  PdfPageFormat pageFormat = PdfPageFormat.a4,
  pw.ThemeData? pdfTheme,
  Uint8List? watermarkBytes,
  double watermarkOpacity = 0.12,
  bool showCgstSgst = false,
  bool showRoundOff = false,
  bool showLeadingZeros = true,
  bool showPhone = true,
  bool showEmail = true,
  bool showCompanyName = true,
  bool showPan = true,
  bool showFssai = true,
  bool showWebsite = true,
  bool showAddress = true,
  bool showLogo = true,
}) {
  final accentColor = themeColor ?? PdfColors.blueGrey800;
  final logoImage = logoBytes != null ? pw.MemoryImage(logoBytes) : null;
  final signatureImage =
      signatureBytes != null ? pw.MemoryImage(signatureBytes) : null;

  pw.Widget partyBlock(String title, List<String> lines,
      {pw.CrossAxisAlignment alignment = pw.CrossAxisAlignment.start}) {
    return pw.Container(
      padding: pw.EdgeInsets.all(executivePdfStyle.sectionPadding),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300, width: 0.7),
        borderRadius: pw.BorderRadius.circular(6),
      ),
      child: pw.Column(
        crossAxisAlignment: alignment,
        children: [
          pw.Text(
            title,
            style: pw.TextStyle(
              color: accentColor,
              fontSize: executivePdfStyle.bodyFontSize,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.SizedBox(height: 6),
          ...lines.where((line) => line.trim().isNotEmpty).map((line) =>
              pw.Text(line, style: pw.TextStyle(fontSize: executivePdfStyle.bodyFontSize))),
        ],
      ),
    );
  }

  final gstin = company?.gstin ?? '';
  final gstLabel = taxLabel(company?.country);
  final panNumber = company?.panNumber ?? '';
  final fssaiCode = company?.fssaiCode ?? '';
  final companyIdLine = [
    if (showGst && gstin.isNotEmpty) '$gstLabel: $gstin',
    if (showPan && panNumber.isNotEmpty) '${panLabel(company?.country)}: $panNumber',
    if (showFssai && fssaiCode.isNotEmpty) 'FSSAI: $fssaiCode',
  ].join('   ');

  final customerLines = [
    invoice.customer.name,
    if (invoice.customer.businessName.isNotEmpty)
      invoice.customer.businessName,
    invoice.customer.address,
    invoice.customer.phone,
    invoice.customer.email,
    if (showGst) '${taxLabel(company?.country)}: ${invoice.customer.gstin}',
  ];

  return pw.MultiPage(
    pageFormat: pageFormat,
    theme: pdfTheme,
    margin: pw.EdgeInsets.all(PdfLayout.defaultHMargin),
    footer: (context) => pw.Container(
      alignment: pw.Alignment.centerRight,
      margin: const pw.EdgeInsets.only(top: 16),
      child: pw.Text(
        showFooterBranding
            ? "Page ${context.pageNumber} of ${context.pagesCount}  -  Generated by Invoiso"
            : "Page ${context.pageNumber} of ${context.pagesCount}",
        style: pw.TextStyle(fontSize: PdfLayout.footerBrandingFontSize, color: PdfColors.grey600),
      ),
    ),
    build: (context) => [
      pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Container(width: 8, height: 96, color: accentColor),
          pw.SizedBox(width: 14),
          if (showLogo && logoImage != null && logoPosition == LogoPosition.left) ...[
            buildCompanyLogo(logoImage, size: logoSizePx),
            pw.SizedBox(width: 14),
          ],
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  showCompanyName ? (company?.name ?? '') : '',
                  style: pw.TextStyle(
                    fontSize: executivePdfStyle.titleFontSize,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.grey900,
                  ),
                ),
                pw.SizedBox(height: executivePdfStyle.headerGap),
                if (showAddress)
                  pw.Text(company?.address ?? '',
                      style: pw.TextStyle(fontSize: executivePdfStyle.subtitleFontSize)),
                if (showPhone)
                  pw.Text('Phone: ${company?.phone ?? ''}',
                      style: pw.TextStyle(fontSize: executivePdfStyle.subtitleFontSize)),
                if (showEmail)
                  pw.Text('Email: ${company?.email ?? ''}',
                      style: pw.TextStyle(fontSize: executivePdfStyle.subtitleFontSize)),
                if (showWebsite && (company?.website ?? '').isNotEmpty)
                  pw.Text(company!.website,
                      style: pw.TextStyle(fontSize: executivePdfStyle.subtitleFontSize)),
                if (companyIdLine.isNotEmpty)
                  pw.Text(companyIdLine, style: pw.TextStyle(fontSize: executivePdfStyle.subtitleFontSize)),
              ],
            ),
          ),
          pw.SizedBox(width: 16),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              if (showLogo && logoImage != null && logoPosition == LogoPosition.right)
                buildCompanyLogo(logoImage, size: logoSizePx),
              pw.SizedBox(height: executivePdfStyle.headerGap),
              if (invoice.pdfNumberText(invoicePrefix, showLeadingZeros: showLeadingZeros) != null)
                pw.Text(
                    '# ${invoice.pdfNumberText(invoicePrefix, showLeadingZeros: showLeadingZeros)}',
                    style: pw.TextStyle(
                        fontSize: executivePdfStyle.bodyFontSize, fontWeight: pw.FontWeight.bold)),
              pw.Text('Date: ${formatPdfDate(invoice.date, datePattern)}',
                  style: pw.TextStyle(fontSize: executivePdfStyle.bodyFontSize)),
              if (invoice.dueDate != null)
                pw.Text('Due: ${formatPdfDate(invoice.dueDate!, datePattern)}',
                    style: pw.TextStyle(fontSize: executivePdfStyle.bodyFontSize)),
            ],
          ),
        ],
      ),
      pw.SizedBox(height: 3),
      pw.Center(child: pw.Text(
        (invoice.invoiceTitle ?? invoice.type).toUpperCase(),
        style: pw.TextStyle(
          fontSize: executivePdfStyle.typeFont,
          fontWeight: pw.FontWeight.bold,
          color: accentColor,
        ),
      ),),
      pw.SizedBox(height: 3),
      pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Expanded(
            child: partyBlock('BILL TO', customerLines),
            flex: 1,
          ),
          pw.Expanded(flex: 1, child: pw.Container()),
        ],
      ),
      pw.SizedBox(height: 5),
      buildInvoiceTable(
        invoice,
        InvoiceTemplate.executive,
        headerColor: accentColor,
        textColor: PdfColors.white,
        showGst: showGst,
        showQuantity: showQuantity,
        showDiscount: showDiscount,
        showTypeTag: showTypeTag,
        showAliasName: showAliasName,
        businessType: businessType,
        watermarkBytes: watermarkBytes,
        watermarkOpacity: watermarkOpacity,
        showCgstSgst: showCgstSgst,
        tableFontSize: executivePdfStyle.tableFontSize
      ),
      pw.SizedBox(height: 5),
      pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Expanded(child: buildAdditionalNotes(invoice, accentColor: accentColor)),
          pw.SizedBox(width: 20),
          buildEnhancedTotals(
            invoice,
            PdfColors.grey200,
            PdfColors.black,
            accentColor,
            currencySymbol,
            previousBalanceDue: previousBalanceDue,
            showCgstSgst: showCgstSgst,
            showRoundOff: showRoundOff,
            fontSize: executivePdfStyle.totalsFontSize
          ),
        ],
      ),
      if (signatureImage != null || (showUpiQr && upiId != null) || bankAccount != null) ...[
        pw.SizedBox(height: 5),
        pw.Row(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: signaturePosition == 'right'
              ? [
                  buildBankUpiRow(
                    bankAccount: bankAccount,
                    showUpiQr: showUpiQr,
                    upiId: upiId,
                    companyName: company?.name ?? '',
                    amount: invoice.total,
                    currencyCode: invoice.currencyCode,
                    invoiceId: invoice.id,
                    accentColor: accentColor,
                  ),
                  signatureImage != null
                      ? buildSignatureWidget(signatureImage, signaturePosition,
                          imageHeight: signatureSizePx)
                      : pw.SizedBox(),
                ]
              : [
                  signatureImage != null
                      ? buildSignatureWidget(signatureImage, signaturePosition,
                          imageHeight: signatureSizePx)
                      : pw.SizedBox(),
                  buildBankUpiRow(
                    bankAccount: bankAccount,
                    showUpiQr: showUpiQr,
                    upiId: upiId,
                    companyName: company?.name ?? '',
                    amount: invoice.total,
                    currencyCode: invoice.currencyCode,
                    invoiceId: invoice.id,
                    accentColor: accentColor,
                  ),
                ],
        ),
      ],
      pw.SizedBox(height: 5),
      pw.Container(height: 2, color: accentColor),
      pw.SizedBox(height: 5),
      pw.Center(
        child: pw.Text(
          thankYouNote,
          style: pw.TextStyle(
            color: accentColor,
            fontSize: PdfLayout.thankYouNoteFontSize,
            fontWeight: pw.FontWeight.bold,
          ),
        ),
      ),
    ],
  );
}
